In [1]:
import numpy as np # 2005 by Travis 

In [2]:
np.__version__

'1.24.3'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
# why numpy
# around 10 thousand+ mathmatical function
# faster

In [9]:
l = [1,2,3,4,5]

In [13]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.ndim

1

In [17]:
l = [1,2,3,4,5,"vijay"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'vijay'], dtype='<U11')

In [18]:
# by default above data has been changed in one type string
type(arr1)

numpy.ndarray

In [19]:
arr1.ndim

1

In [20]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 3)

In [28]:
arr2[0:2,1:2]

array([[2],
       [5]])

In [30]:
l = [1,2,3,4]

In [37]:
np.array(l)

array([1, 2, 3, 4])

In [33]:
l1 = np.matrix(l)
l1

matrix([[1, 2, 3, 4]])

In [34]:
type(l1)

numpy.matrix

In [35]:
l1.ndim

2

In [36]:
l1.shape

(1, 4)

# matrix will be by default 2D

In [38]:
# more way to convert to array
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [39]:
np.asanyarray([[[1,2],[3,4],[5,6]]]) # convert the input to an ndarray,but pass ndarray subclass

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [40]:
mat = np.matrix([1,2,3,4,5])
mat

matrix([[1, 2, 3, 4, 5]])

In [41]:
np.asanyarray(mat)
# it is matrix not converted any array

matrix([[1, 2, 3, 4, 5]])

In [42]:
# convert tuple into array

In [43]:
t = (2,3,4,5)
type(t)

tuple

In [44]:
np.array(t)
# np.asarray(t)
# np.asanyarray(t)

array([2, 3, 4, 5])

In [45]:
np.asarray(t)

array([2, 3, 4, 5])

In [46]:
np.asanyarray(t)

array([2, 3, 4, 5])

In [47]:
#  we can convert any scaler value into array
# 3D array widely used in image processing
a = 5
np.array(5)

array(5)

In [49]:
arr3 = arr5=[1,2,3,4]
# shallow copy , both will changed

In [50]:
arr3

[1, 2, 3, 4]

In [51]:
arr5


[1, 2, 3, 4]

In [53]:
arr3[2] = 34

In [54]:
arr3

[1, 2, 34, 4]

In [55]:
arr5

[1, 2, 34, 4]

In [64]:
arr1 = [2,4,6,8]
arr2 = arr1.copy()
# deep copy not other will not changed

In [57]:
arr2

[2, 4, 6, 8]

In [58]:
arr1

[2, 4, 6, 8]

In [59]:
arr1[1] = 45

In [60]:
arr1

[2, 45, 6, 8]

In [61]:
arr2

[2, 4, 6, 8]

 # There are mutiple way to generate array

In [62]:
np.fromfunction(lambda i,j:i==j , shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [65]:
arr1

[2, 4, 6, 8]

In [ ]:
# shape will give dimension
# size will give total number of element

In [68]:
np.fromfunction(lambda i, j: i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [73]:
np.fromfunction(lambda i,j : i+j<10, shape=(3,1))

array([[ True],
       [ True],
       [ True]])

In [74]:
for i in range(5):
    print(i)

0
1
2
3
4


In [75]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [90]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [76]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [77]:
list(range(5))

[0, 1, 2, 3, 4]

In [80]:
iterable = (i*i for i in range(5))

In [81]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [85]:
np.fromstring('23 34 56 78' , sep =' ')
# sep--> sepretable

array([23., 34., 56., 78.])

In [86]:
np.fromstring('23,34,56,99',sep=',')

array([23., 34., 56., 99.])

In [87]:
np.fromstring('vijay,ambresh,prabhat,ajeet',sep=',')
# it will not covert we need to pass number

C:\Users\vijay\AppData\Local\Temp\ipykernel_22628\1409307748.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('vijay,ambresh,prabhat,ajeet',sep=',')


array([], dtype=float64)

In [96]:
l = [1,2,3,4]
arr = np.array(l)

In [97]:
arr

array([1, 2, 3, 4])

In [99]:
arr.dtype

dtype('int32')

In [100]:
arr.shape

(4,)

In [93]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [92]:
range(0,5)

range(0, 5)

In [94]:
list(range(1.0,2.1))

TypeError: 'float' object cannot be interpreted as an integer

 range float will not interpreted as in integer
# how we can solve it

In [103]:
list(np.arange(0.1,2.1,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004]

In [106]:
list(np.linspace(1,5,20))
# it does not take random value

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [108]:
np.logspace(1,5,10,base = 2)
# log value
# from 1 to 5 generate 10 value with log of base 2

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
# logspace will give you equdistent
# linspace will give exact value

In [114]:
arr1= np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [116]:
arr1.ndim

1

In [115]:
arr2 = np.zeros((3,4))
# arr2 = np.zeros((3,4),int)
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
arr2.ndim

2

In [118]:
arr2.shape

(3, 4)

In [120]:
arr2.size

12

In [124]:
arr3 = np.zeros((3,3,4))
#  here 3 dimension array,3 row, 4 column
# repeate 3,4 in 3 time or 3 axis
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [125]:
arr3.ndim

3

In [126]:
arr3.shape

(3, 3, 4)

In [132]:
arr4 = np.zeros((1,3,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [133]:
arr4.ndim

4

In [134]:
arr4.shape

(1, 3, 3, 4)

In [135]:
type(arr4)

numpy.ndarray

# Ones

In [136]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [139]:
arr1= np.ones((4,1))
arr1

array([[1.],
       [1.],
       [1.],
       [1.]])

In [140]:
arr1 + 3

array([[4.],
       [4.],
       [4.],
       [4.]])

In [142]:
arr1*5

array([[5.],
       [5.],
       [5.],
       [5.]])

In [2]:
arr = np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
arr*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [13]:
np.empty((3,4))
# it will give any random value

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [14]:
np.empty((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.eye(4)
# all will give square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
# optional 
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [19]:
# extra topic
import random

In [29]:
a = random.choice((1,2,3,4,5,6,'vijay'))
a

4

In [30]:
type(a)

int

In [31]:
random.choice("vijay")

'v'

In [35]:
random.randrange(1,50)

36

In [34]:
random.random()

0.4664213769260842

In [36]:
lis = [3,4,5,8]
random.shuffle(lis)

In [37]:
lis

[3, 5, 8, 4]

# We can use Random in Numpy also without using Liberary

In [38]:
np.random.rand(2,3)

array([[0.86562017, 0.87171076, 0.52638149],
       [0.12802093, 0.35876508, 0.19834525]])

In [39]:
np.random.rand(1)

array([0.38279266])

In [40]:
np.random.randn(2,3)
# random normal distribution

array([[ 0.07735605, -0.07075028, -0.11280792],
       [-0.43772422, -1.51947697, -0.27067404]])

In [41]:
np.random.random_sample()
# here random value

0.8212311293285542

In [4]:
arr1= np.random.randint(1,5,size=(3,4))
# generate random value from 1 to 5 and size should 3 X 4

In [5]:
arr1

array([[2, 2, 4, 2],
       [4, 4, 2, 4],
       [4, 2, 2, 2]])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(3, 4)

In [8]:
arr1.ndim

2

In [9]:
# reshape the above array
arr1.reshape(2,6)
# array size can not change,value should be multiple of array size

array([[2, 2, 4, 2, 4, 4],
       [2, 4, 4, 2, 2, 2]])

In [10]:
arr1.reshape(12,)

array([2, 2, 4, 2, 4, 4, 2, 4, 4, 2, 2, 2])

In [11]:
arr1.reshape(4,-1)
# i don't know number of column then -1(any -ve) , it will takecare

array([[2, 2, 4],
       [2, 4, 4],
       [2, 4, 4],
       [2, 2, 2]])

# array.reshape() will be deepcopy or shallow copy
Shallow copy

In [12]:
arr1.reshape(12,1).base
# for origional array

array([[2, 2, 4, 2],
       [4, 4, 2, 4],
       [4, 2, 2, 2]])

In [2]:
import numpy as np

In [13]:
arr1 = np.random.randint(1,5,size=(3,4))

In [16]:
arr1

array([[4, 4, 2, 1],
       [4, 1, 4, 2],
       [1, 4, 1, 3]])

In [17]:
arr1.reshape(2,2,3)

array([[[4, 4, 2],
        [1, 4, 1]],

       [[4, 2, 1],
        [4, 1, 3]]])

In [18]:
arr1.ndim

2

In [19]:
arr1.reshape(1,1,1,1,1,1,2,2,3)

array([[[[[[[[[4, 4, 2],
              [1, 4, 1]],

             [[4, 2, 1],
              [4, 1, 3]]]]]]]]])

In [20]:
arr2 = np.array([[2,3],[4,5]])

In [21]:
arr2

array([[2, 3],
       [4, 5]])

In [22]:
arr3 = np.zeros((1,3,4))
# 3 row, 4 column, 2d array + 1d +1d

In [18]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
arr4 = np.zeros((2,3,4))
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
arr4.shape

(2, 3, 4)

In [25]:
arr3.ndim

3

In [26]:
arr5 = np.random.randint(1,10,(5,6))

In [23]:
arr5

array([[3, 5, 4, 3, 1, 3],
       [9, 9, 5, 6, 4, 2],
       [2, 7, 1, 2, 5, 9],
       [3, 1, 3, 5, 6, 1],
       [1, 8, 8, 6, 7, 3]])

In [27]:
arr5>5

array([[False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False],
       [ True, False, False, False,  True, False],
       [ True, False, False,  True,  True, False],
       [False,  True,  True, False,  True, False]])

In [28]:
arr5[arr5>5]
# exact value given where condition true

array([6, 9, 8, 8, 9, 7, 9, 6, 6, 7, 9, 6, 9, 6, 6, 9])

In [29]:
arr5[0]

array([5, 6, 9, 8, 8, 9])

In [30]:
arr5[0:]

array([[5, 6, 9, 8, 8, 9],
       [7, 1, 9, 6, 5, 5],
       [6, 3, 3, 1, 7, 3],
       [9, 2, 1, 6, 9, 2],
       [2, 6, 6, 3, 9, 4]])

In [33]:
arr2= np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [34]:
arr2.ndim

2

In [35]:
arr2= np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr3 = np.zeros((1,3,4)) # 3row,4column >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
arr3.shape

(1, 3, 4)

In [39]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
arr3.ndim

3

In [41]:
arr3.shape

(2, 3, 4)

In [42]:
arr1 = np.random.randint(1,10,(5,6))

In [43]:
arr1

array([[3, 4, 1, 1, 6, 1],
       [1, 7, 5, 6, 2, 4],
       [2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2],
       [6, 8, 3, 4, 6, 7]])

In [44]:
arr1>5

array([[False, False, False, False,  True, False],
       [False,  True, False,  True, False, False],
       [False,  True,  True,  True,  True,  True],
       [False,  True, False, False, False, False],
       [ True,  True, False, False,  True,  True]])

In [45]:
arr1[arr1>5]
# to find exact value

array([6, 7, 6, 6, 9, 7, 6, 9, 8, 6, 8, 6, 7])

In [47]:
arr1

array([[3, 4, 1, 1, 6, 1],
       [1, 7, 5, 6, 2, 4],
       [2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2],
       [6, 8, 3, 4, 6, 7]])

In [48]:
arr1[0,[1,3]]

array([4, 1])

In [49]:
# from second row to forth row
arr1[2:4,[2,3]]

array([[9, 7],
       [1, 3]])

In [51]:
arr1[0:4]

array([[3, 4, 1, 1, 6, 1],
       [1, 7, 5, 6, 2, 4],
       [2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2]])

In [52]:
arr1[2:5]

array([[2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2],
       [6, 8, 3, 4, 6, 7]])

In [54]:
arr1[2:5,0:2] # slicing 
# it will return from  value from 2 row to 5 column and with 0row-->2column

array([[2, 6],
       [3, 8],
       [6, 8]])

In [55]:
arr1[2:5,[0,2]]
# it will return exact from 2row-->5row, column0 and column1
# it will give specific value

array([[2, 9],
       [3, 1],
       [6, 3]])

In [56]:
arr1

array([[3, 4, 1, 1, 6, 1],
       [1, 7, 5, 6, 2, 4],
       [2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2],
       [6, 8, 3, 4, 6, 7]])

In [57]:
arr1[[2,4]]

array([[2, 6, 9, 7, 6, 9],
       [6, 8, 3, 4, 6, 7]])

In [58]:
arr1[2:4]

array([[2, 6, 9, 7, 6, 9],
       [3, 8, 1, 3, 4, 2]])

In [ ]:
# slicing----> arr1[2:4]
# specific value ---> arr1[2,4]

In [59]:
arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [60]:
arr1

array([[2, 3, 1],
       [2, 4, 3],
       [3, 4, 3]])

In [61]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [62]:
arr1 + arr2
# index wise addition

array([[4, 5, 2],
       [4, 5, 4],
       [4, 6, 4]])

In [63]:
arr1 * arr2
# multipication of matrix index wise

array([[4, 6, 1],
       [4, 4, 3],
       [3, 8, 3]])

In [65]:
# matrix multipication
arr1@arr2

array([[11,  9,  6],
       [15, 14,  9],
       [17, 16, 10]])

# Broad Casting 
radio

In [68]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr + 5 # this broad casting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [76]:
a = np.array([1,2,3,4])

In [77]:
a

array([1, 2, 3, 4])

In [78]:
arr + a
# column wise we can add 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [87]:
# add column wise
a1 = np.array([[1,2,3]])
# process---> Transpose of a1(a1.T) + arr

In [88]:
a1

array([[1, 2, 3]])

In [89]:
# transpose of a1
a1.T

array([[1],
       [2],
       [3]])

In [91]:
arr + a1.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [92]:
arr1

array([[2, 3, 1],
       [2, 4, 3],
       [3, 4, 3]])

In [96]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.        ],
       [1.41421356, 2.        , 1.73205081],
       [1.73205081, 2.        , 1.73205081]])

In [94]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692,  2.71828183],
       [ 7.3890561 , 54.59815003, 20.08553692],
       [20.08553692, 54.59815003, 20.08553692]])

In [95]:
np.log(arr1)

array([[0.69314718, 1.09861229, 0.        ],
       [0.69314718, 1.38629436, 1.09861229],
       [1.09861229, 1.38629436, 1.09861229]])

In [97]:
np.max(arr1)

4

# Dimension

In [99]:
arr1.flatten()
# its reduce high dimension to low dimension
# by default it will give one dimension array

array([2, 3, 1, 2, 4, 3, 3, 4, 3])

# expand_dims
>> expands the array by inserting a new axis
>> use in lots image processing

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(arr)

45

In [5]:
np.sum(arr,axis =0)
# this addition rowwise

array([12, 15, 18])

In [6]:
# this column wise addition
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [7]:
arr1 = np.expand_dims(arr,axis=0)
arr1
# it will become 2D--->3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
# expand_dims >> expand the dimension of array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
arr.ndim

1

In [12]:
arr1 = np.expand_dims(arr,axis=0) # axis=0 ----> row , axis=1 vertical
arr1
# it will become 1D--->2D

array([[1, 2, 3, 4]])

In [13]:
arr1.ndim

2

In [14]:
arr2 = np.expand_dims(arr1,axis=0)
arr2

array([[[1, 2, 3, 4]]])

In [15]:
arr2.ndim

3

In [16]:
arr1 = np.expand_dims(arr,axis=1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [3]:
data = np.array([[1],[2],[3],[4]])

In [4]:
data

array([[1],
       [2],
       [3],
       [4]])

In [10]:
data.ndim

2

In [6]:
a = np.squeeze(data)
a

array([1, 2, 3, 4])

In [9]:
a.ndim

1

In [11]:
arr = np.array([[[1,2],[3,4],[5,6]]])
arr

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [12]:
arr.ndim

3

In [14]:
np.squeeze(arr)
# it will reduce one dimension means 3D ----> 2D or 2D--->1D

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# repeat
data

array([[1],
       [2],
       [3],
       [4]])

In [17]:
arr2= np.repeat(data,4)
arr2

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [18]:
arr2.ndim

1

In [19]:
arr3 = np.repeat(arr,2)
arr3

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [20]:
arr3.ndim

1

In [21]:
np.repeat(arr,2,axis=1) # repeated column wise

array([[[1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [5, 6],
        [5, 6]]])

In [26]:
np.repeat(arr,2,axis=2)

array([[[1, 1, 2, 2],
        [3, 3, 4, 4],
        [5, 5, 6, 6]]])

In [ ]:
# repeat(data,no. of repeat) ---> used repeat the data

In [29]:
arr

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [28]:
np.roll(arr,2)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [30]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# binary operation on array

In [31]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [33]:
arr1

array([[2, 4, 1, 1],
       [5, 2, 3, 7],
       [4, 5, 8, 4]])

In [34]:
arr2

array([[9, 5, 7, 7],
       [4, 6, 1, 5],
       [5, 7, 1, 5]])

In [32]:
arr1 + arr2 # index wise addition
# arr1 * arr2 index wise multipication

array([[11,  9,  8,  8],
       [ 9,  8,  4, 12],
       [ 9, 12,  9,  9]])

In [35]:
arr1>arr2

array([[False, False, False, False],
       [ True, False,  True,  True],
       [False, False,  True, False]])

In [36]:
arr1**arr2

array([[  512,  1024,     1,     1],
       [  625,    64,     3, 16807],
       [ 1024, 78125,     8,  1024]])

In [37]:
~arr1 # negation of arr1

array([[-3, -5, -2, -2],
       [-6, -3, -4, -8],
       [-5, -6, -9, -5]])

# numpy string function

In [39]:
arr = np.array(['pw','skills'])
arr

array(['pw', 'skills'], dtype='<U6')

In [40]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [41]:
np.char.upper(np.array(['Vijay']))

array(['VIJAY'], dtype='<U5')

In [42]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [43]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

# mathmatical function we directly use

In [48]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [49]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [50]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
np.mean(arr)

2.5

In [52]:
np.max(arr)

4

In [54]:
np.multiply(arr1,arr1)

array([[ 4, 16,  1,  1],
       [25,  4,  9, 49],
       [16, 25, 64, 16]])

# sort and searching 

In [55]:
arr = np.array([3,2,7,4,1])
arr

array([3, 2, 7, 4, 1])

In [56]:
np.sort(arr)

array([1, 2, 3, 4, 7])

In [67]:
np.searchsorted(arr,10)

5

In [61]:
arr1 = np.array([0,1,2,3,34,0,4])
np.count_nonzero(arr1)

5

In [62]:
arr1>0

array([False,  True,  True,  True,  True, False,  True])

In [63]:
arr1[arr1>0]

array([ 1,  2,  3, 34,  4])

In [64]:
np.where(arr1>0)

(array([1, 2, 3, 4, 6], dtype=int64),)

In [65]:
np.extract(arr1>0,arr1)

array([ 1,  2,  3, 34,  4])

In [68]:
arr1

array([ 0,  1,  2,  3, 34,  0,  4])

In [69]:
arr1.byteswap()
# how data are store 

array([        0,  16777216,  33554432,  50331648, 570425344,         0,
        67108864])

# matrix >> 2D aray

In [70]:
import numpy.matlib as nm

In [71]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [72]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Numpy Linear algebra

In [74]:
arr1 = np.array([[2,3],[4,5]])
arr2 = np.array([[6,3],[4,2]])

In [75]:
arr1 @ arr2 # matrix multipication

array([[24, 12],
       [44, 22]])

In [ ]:
"""
7x + 5y -3z = 16
2x -5y + 2z = -8
5x + 3y - 7z = 0
find x,y,z ?

"""

In [76]:
a = np.array([[7,5,-3],[2,-5,2],[5,3,-7]]) # LHS value
b = np.array([16,-8,0]) # RHS value

In [77]:
np.linalg.solve(a,b)

array([1.11304348, 2.85217391, 2.0173913 ])

# Inverse of matrix
Invers of A = | A | / det(A)

In [85]:
A = np.array([[2,3],[4,5]])
A

array([[2, 3],
       [4, 5]])

In [86]:
np.linalg.det(A)

-2.0

In [87]:
np.linalg.inv(A)

array([[-2.5,  1.5],
       [ 2. , -1. ]])